### ISSUE TITLE
Return value for OAuth support

### ISSUE THREAD

**Issue by kremerpatrick** [vmware/python-client-for-vmware-cloud-on-aws#140]
### Describe the bug

Line 790 of pyVMC.py does an exit(1) if incorrect args are provided to getAccessToken()

Line 5804-5805 checks for a None return value from getAccessToken() and does s sys.exit(1)

Line 790 should not exit(1), it should return None.

### Reproduction steps

Any invocation of the program with invalid credentials

### Expected behavior

Line 790 of pyVMC.py should not exit(1), it should return None.

**Comment by fr0gger03** [comment]
Patrick - I believe we decided on sys.exit(1) for the test harness Bill is adding. I will ask him to chime in.

**Comment by kremerpatrick** [comment]
Regardless of why sys.exit(1) was put on 5805, there should not be an exit statement inside of getAccessToken(). It should return None on error.

No issue with the sys.exit() on 5805 - you're not getting anywhere in this program without successful authentication.

**Comment by mandarb80** [comment]
Completely agree with your comment. Will make that change along with some doc updates in next pull request. Will close this bug once its merged.

**Comment by mandarb80** [comment]
@kremerpatrick with latest merge, sys.exit has been changed to return None.

**Comment by kremerpatrick** [comment]
Closed by #141
