### ISSUE TITLE
Add subcommand for connecting vTGW to external TGW

### ISSUE THREAD

**Issue by mithil2906** [vmware/python-client-for-vmware-cloud-on-aws#181]
### Is your feature request related to a problem? Please describe.

Currently there is no subcommand to peer vTGW with external TGW:

 vtc sub-command help
    get-task-status                     Get status of the current task.
    connect-aws                         Connect an vTGW to an AWS account
    disconnect-aws                      Disconnect a vTGW from an AWS account
    attach-dxgw                         Attach a Direct Connect Gateway to a vTGW
    detach-dxgw                         Detach a Direct Connect Gateway from a vTGW
    get-deployments                     Display a list of all SDDCs
    get-nsx-info                        Display NSX credentials and URLs
    attach-sddc                         Attach an SDDC to a vTGW
    detach-sddc                         Detach an SDDC from a vTGW
    create-sddc-group                   Create an SDDC group
    delete-sddc-group                   Delete an SDDC group
    get-group-info                      Display details for an SDDC group
    attach-vpc                          Attach a VPC to a vTGW
    detach-vpc                          Detach VPC from a vTGW
    vpc-prefixes                        Add or remove static routes to your vTGW.

### Describe the solution you'd like

A subcommand to peer vTGW with External TGW is desired

**Comment by maulepilot117** [comment]
Enhancement tracked by Issue #164
