### ISSUE TITLE
PyVMC v2.0 beta - command missing

### ISSUE THREAD

**Issue by mixologee** [vmware/python-client-for-vmware-cloud-on-aws#186]
### Describe the bug

pyVMC.py sddc get-access-token does not return the access token

### Reproduction steps

1. ./pyVMC.py sddc get-access-token

### Expected behavior

get-access-token: show your access token

**Comment by maulepilot117** [comment]
Hi, get-access-token is not currently a function supported by pyVMC.

**Comment by maulepilot117** [comment]
No worries!  If there is a use-case for it, I'm sure it's something we can add to the backlog.
