### ISSUE TITLE
segment update -n <segment> -conn ON/OFF doesn't work

### ISSUE THREAD

**Issue by dlp-aws** [vmware/python-client-for-vmware-cloud-on-aws#189]
### Describe the bug

When updating an existing network segment that is disconnected to connected, the CLI fails when either using the "-conn ON" flag or the "-rt ROUTED" flag.

### Reproduction steps

1. Start with a disconnected network segment
2. run "$./pyVMC.py segment update -n NETWORK_NAME -conn ON" or "$./pyVMC.py segment update -n NETWORK_NAME -rt ROUTED"
3. The first command will fail and the second will say the network segment is updated but it won't be.

### Expected behavior

The network segment should get updated to be routed.

**Comment by fr0gger03** [comment]
Hey David!  When you are using the "-n" parameter are you also passing the segment ID or name?

**Comment by dlp-aws** [comment]
Yes, my apologies, I copy/pasted it incorrectly. I did enter "-n <segment name>"

**Comment by maulepilot117** [comment]
Hey David, which version of the SDDC were you testing against?

**Comment by dlp-aws** [comment]
> Hey David, which version of the SDDC were you testing against?

M22
