### ISSUE TITLE
delete T1 doesn't validate the name

### ISSUE THREAD

**Issue by dlp-aws** [vmware/python-client-for-vmware-cloud-on-aws#190]
### Describe the bug

When trying to delete an additional T1 gateway, there is no validation of the name provided. The code should throw an error if the name given doesn't exist. If a customer fat-fingers the network name and expects it to be deleted, they'll think it was because the CLI will exit successfully.

### Reproduction steps

1. "./pyVMC.py t1 delete -n <network name that doesn't exist>"
2. This will result in "Tier1 gateway <network name that doesn't exist> has been deleted."

### Expected behavior

It should throw an error stating "<network name> does not exist".

**Comment by maulepilot117** [comment]
Completely agree we should be validating the T1 exists prior to attempting the deletion.  Added this to feature request for the pyVMC 2.1 release.
