### ISSUE TITLE
-aws option in sddc create should accept the AWS account ID instead of GUID

### ISSUE THREAD

**Issue by mithil2906** [vmware/python-client-for-vmware-cloud-on-aws#193]
### Is your feature request related to a problem? Please describe.

If I try to pass AWS account ID to the option -aws to the cli sddc create, it fails and expects it to be a guid. Getting a GUID is cumbersome as users has to get the value from "/orgs/{{orgid}}/account-link/connected-accounts". It would be straightforward if aws account id is passed instead of GUID (that is the case in other cli and sub-commands)

mithilra@b0be83701edd python-client-for-vmware-cloud-on-aws-development % ./pyVMC.py sddc create -n mithilra-1node-sddc -r us-east-1 -num 1 -t i3.metal -sid subnet-04d122190192cd7fa -mgt 10.9.0.0/16 -s medium -aws 310793149708 -v
Error Code 400: Bad Request, Bad URL or Quota Violation
Bad request (e.g. missing request body).

### Describe the solution you'd like

It would be straightforward if aws account id is passed instead of GUID (that is the case in other cli and sub-commands)

**Comment by maulepilot117** [comment]
Currently, the way the API works under the covers is to utilize the account GUID versus the Account ID.  We can look into adding logic to accept the customer's Account ID and match to the account GUID, but that will be a larger lift than what's planned for the 2.0 release.  We'll add this a feature request for the 2.5 release.
