### ISSUE TITLE
new function for learned and advertised routes

### ISSUE THREAD

**Issue by fr0gger03** [vmware/python-client-for-vmware-cloud-on-aws#43]
This will provide the ability to quickly verify if prefix filters are working as desired without entering the console web UI

Learned / advertised routes:
    * GET /policy/api/v1/infra/tier-0s/<tier-0-id>/locale-services/<locale-service-id>/bgp/neighbors/<neighbor-id>/advertised-routes
    * GET /policy/api/v1/infra/tier-0s/<tier-0-id>/locale-services/<locale-service-id>/bgp/neighbors/<neighbor-id>/routes

**Comment by kremerpatrick** [comment]
1af8c8de800b07701f874da5c2171803253cd955
