### ISSUE TITLE
Update README.md with latest commands

### ISSUE THREAD

**Issue by fr0gger03** [vmware/python-client-for-vmware-cloud-on-aws#45]
need to include the following in README under "BGP and Networking":
- attach-t0-prefix-list [BGP NEIGHBOR ID]: attach a BGP Prefix List to a T0 BGP neighbor
- detach-t0-prefix-lists [BGP NEIGHBOR ID]: detach all prefix lists from specified neighbor

**Comment by kremerpatrick** [comment]
aa12e25
