### ISSUE TITLE
When SDDC has multiple clusters the hosts are only displayed from the first one. 

### ISSUE THREAD

**Issue by fuatu** [vmware/python-client-for-vmware-cloud-on-aws#5]
When SDDC has multiple clusters the hosts are only displayed from the first one. 
fixed this issue under 
"fix host display for multiple clusters in same SDDC #4" pull request.

Another thing is that the requirements.txt was not there and the people need to fish the dependencies. 
`pip install -r requirements" can be used now. 
I added that. 

As a good practice putting example files for files "config.ini" (as this has token) and excluding these files in .gitignore is a better approach so I added also these details.

**Comment by fuatu** [comment]
Hi @kremerpatrick 
I also fixed the issue in show_sddcs in the pull request.

**Comment by nvibert** [comment]
Issue can be closed.

Pull request merged. 

Thanks again for your contributions Fuat.
