### ISSUE TITLE
New-Group examples are missing info

### ISSUE THREAD

**Issue by eshanks16** [vmware/python-client-for-vmware-cloud-on-aws#68]
### Describe the bug

Attempted to use a new-group call based on the examples but received syntax errors.

### Reproduction steps

```bash
1. pyVMC.py new-group cgw test 10.10.10.10

Result
Incorrect syntax. Make sure you use one of the 4 methods to define a CGW group: ip-based, member-based, criteria-based, or group-based.
```

### Expected behavior

A new group should've been created.

### Additional context

I think there are additional switches that need to be added such as ip-based, etc in the readme.

**Comment by kremerpatrick** [comment]
Pushed updated README
