### ISSUE TITLE
Feature request: Add options for creating a new SDDC

### ISSUE THREAD

**Issue by kremerpatrick** [vmware/python-client-for-vmware-cloud-on-aws#69]
### Is your feature request related to a problem? Please describe.

Make it easier to build a new SDDC

### Describe the solution you'd like

Create some commands to build a new SDDC

**Comment by BillRothVMware** [comment]
I'll take a look at this one.

**Comment by BillRothVMware** [comment]
Note since this will be done in the background, (the api returns a task id), I'll need to implement a a task watcher/poller.
